<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>recon</AssemblyName>
    <RootNamespace>InvestigationNightmares.Recon</RootNamespace>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\InvestigationNightmares.Core\InvestigationNightmares.Core.csproj" />
  </ItemGroup>
</Project>
