#!/usr/bin/env python3
"""Generate C# from the sheets: one record per row, built from that row's columns.

Output: src/InvestigationNightmares.Core/Generated/Sheets.g.cs
Refuses to generate while preflight reports errors.
"""
import json
import sys

from sheets import ROOT, load_sheets, preflight

OUT = ROOT / "src" / "InvestigationNightmares.Core" / "Generated" / "Sheets.g.cs"


def pascal(name):
    return "".join(p[:1].upper() + p[1:] for p in name.split("_"))


def cs_type(col):
    t = col["type"]
    base = {"id": "string", "string": "string", "ref": "string", "enum": "string",
            "int": "int", "number": "double", "bool": "bool", "refs": "string[]"}[t]
    return base + ("?" if col.get("nullable") else "")


def cs_literal(col, v):
    if v is None:
        return "null"
    t = col["type"]
    if t == "bool":
        return "true" if v else "false"
    if t == "int":
        return str(v)
    if t == "number":
        return repr(float(v))
    if t == "refs":
        return "new[] { " + ", ".join(json.dumps(x) for x in v) + " }"
    return json.dumps(v, ensure_ascii=False)


def main():
    sheets = load_sheets()
    errors, _ = preflight(sheets)
    if errors:
        print(f"gen_code: preflight has {len(errors)} errors; run tools/preflight.py", file=sys.stderr)
        sys.exit(1)

    out = ["// <auto-generated> from sheets/*.json by tools/gen_code.py. Edit the sheets, not this file. </auto-generated>",
           "#nullable enable",
           "using System.Collections.Generic;",
           "",
           "namespace InvestigationNightmares.Generated;",
           ""]
    for name, sheet in sheets.items():
        rec = pascal(name) + "Row"
        params = [f"{cs_type(d)} {pascal(c)}" for c, d in sheet["columns"].items()]
        params.append("string[] Unverified")
        out.append(f"/// <summary>{sheet['description']}</summary>")
        out.append(f"public sealed record {rec}({', '.join(params)});")
        out.append("")

    out.append("public static class Sheets")
    out.append("{")
    for name, sheet in sheets.items():
        rec = pascal(name) + "Row"
        prop = pascal(name)
        out.append(f"    public static readonly IReadOnlyList<{rec}> {prop} = new {rec}[]")
        out.append("    {")
        for row in sheet["rows"]:
            args = [cs_literal(d, row[c]) for c, d in sheet["columns"].items()]
            unv = row.get("_unverified", [])
            args.append("new string[] { " + ", ".join(json.dumps(u) for u in unv) + " }")
            out.append(f"        new({', '.join(args)}),")
        out.append("    };")
        out.append("")
    out.append("}")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"gen_code: wrote {OUT.relative_to(ROOT)} ({len(sheets)} sheets)")


if __name__ == "__main__":
    main()
